# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kall < Formula
  desc "Run commands across multiple projects in parallel"
  homepage "https://github.com/kanetran29/kall"
  version "2.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.2/kall_2.1.2_darwin_amd64.tar.gz"
      sha256 "992728ce0be3d7d4f95502e4dc207f2c207a25e9953cd7720788a3e06832f807"

      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.2/kall_2.1.2_darwin_arm64.tar.gz"
      sha256 "4807196e3426a1caf3e4d0ded49236a8be60dd7e66b8a70de56c2aae061094f5"

      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.2/kall_2.1.2_linux_amd64.tar.gz"
      sha256 "4ef0757de4aee1a1dd14eaa2e5f30228ff335f723634b48fd8c62007be412014"
      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.2/kall_2.1.2_linux_arm64.tar.gz"
      sha256 "c860aa330f656db343f15d3d45683928a2e2bd51cb6373c4c0e4a95f61fa1395"
      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kall --version")
  end
end
