# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kall < Formula
  desc "Run commands across multiple projects in parallel"
  homepage "https://github.com/kanetran29/kall"
  version "2.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.6/kall_2.1.6_darwin_amd64.tar.gz"
      sha256 "a54b4844de78208962deabbf6d12e5ce2c9c10a2886a47bcd334cd7a0d2b58f1"

      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.6/kall_2.1.6_darwin_arm64.tar.gz"
      sha256 "9d0ccd7029fc40450a4eb1378d9fa986a8a19d67dc4b3fb0c74d166e8edebb04"

      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.6/kall_2.1.6_linux_amd64.tar.gz"
      sha256 "257213a0cbb846c5c0c9ba4fe28e36bcb527f66af94f688fce085f7cbd604d2c"
      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.6/kall_2.1.6_linux_arm64.tar.gz"
      sha256 "6e7e0de2ee22dca64e7f29053b11223070927e1b58a41d6342aa36c755ea2967"
      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kall --version")
  end
end
