# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kall < Formula
  desc "Run commands across multiple projects in parallel"
  homepage "https://github.com/kanetran29/kall"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanetran29/kall/releases/download/v2.3.0/kall_2.3.0_darwin_amd64.tar.gz"
      sha256 "ba13d791b6cba236c708f2295a7de1a7fe791748ce0b9a1e535309f383d5292b"

      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanetran29/kall/releases/download/v2.3.0/kall_2.3.0_darwin_arm64.tar.gz"
      sha256 "502a7f028947e7e416cec2fdbe50152d36224d9738a025530092201fd570029a"

      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanetran29/kall/releases/download/v2.3.0/kall_2.3.0_linux_amd64.tar.gz"
      sha256 "ff8ef7e06edb88d0473e03bfe3531a12457e4dc461bd01de6cdb7841422d37e8"
      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanetran29/kall/releases/download/v2.3.0/kall_2.3.0_linux_arm64.tar.gz"
      sha256 "ab421724f0f1b339e0f63bc08e1d6a99fc8dc50af9b330d5c49e983cd6085084"
      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kall --version")
  end
end
