# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kall < Formula
  desc "Run commands across multiple projects in parallel"
  homepage "https://github.com/kanetran29/kall"
  version "2.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.5/kall_2.1.5_darwin_amd64.tar.gz"
      sha256 "91283d1fb952d5d6c4fa50d89f847aeb25dfa15bc9e629182c3018c505fdd05d"

      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.5/kall_2.1.5_darwin_arm64.tar.gz"
      sha256 "fd2c30e2787a48fea575a3af7d32bd6987d56068f7a982fc98f2ce1441326655"

      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.5/kall_2.1.5_linux_amd64.tar.gz"
      sha256 "acb2d2a0833d93037e011d1eb9109180b04ece3a916e54a1d301ec38e3efbd94"
      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kanetran29/kall/releases/download/v2.1.5/kall_2.1.5_linux_arm64.tar.gz"
      sha256 "eac6aa4c4315712cea85e217960b5848c99f96c8bec277fb2420391ce73f5f42"
      define_method(:install) do
        bin.install "kall"
        man1.install "man/kall.1"
        bash_completion.install "completions/kall.bash" => "kall"
        zsh_completion.install "completions/_kall"
        fish_completion.install "completions/kall.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kall --version")
  end
end
